language: objective-c

osx_image: xcode9
script:
- xcrun  instruments -w "iPhone 7 (11.0) [5BABCDC9-5EAF-4E60-96C0-F78309091348] (Simulator)" || true

- xcodebuild -workspace SASeatBooking.xcworkspace -scheme SASeatBooking -destination 'platform=iOS Simulator,name=iPhone 8' -sdk iphonesimulator

notifications:
  slack: 'samedialabs:$SLACK_SAMEDIALABS_TRAVIS_CI'

