language: objective-c

osx_image: xcode10
script:
- xcrun  instruments -w "iPhone 7 (11.0) [5BABCDC9-5EAF-4E60-96C0-F78309091348] (Simulator)" || true

- xcodebuild -workspace SASeatBooking.xcworkspace -scheme SASeatBooking -destination 'platform=iOS Simulator,name=iPhone 8' -sdk iphonesimulator build CODE_SIGNING_REQUIRED=NO  ONLY_ACTIVE_ARCH=NO  RUN_CLANG_STATIC_ANALYZER=YES GCC_TREAT_WARNINGS_AS_ERRORS=YES

notifications:
  slack: 'samedialabs:$SLACK_SAMEDIALABS_TRAVIS_CI'

